server:
  port: 9090

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/parking?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    connect-timeout: 30000ms

# 配置mybatis实体和xml映射
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

fileBaseUrl: http://localhost:${server.port}


# 邮件服务器配置
mail:
  smtp:
    # 邮件服务器主机地址
    host: smtp.163.com
    # 邮件服务器端口号
    port: 465
    # 邮件发送账号（邮箱地址）
    username: 13818337845@163.com
    # 邮件发送授权码（非邮箱密码） # MBrai352U9iXnbnY
    password: MBrai352U9iXnbnY
    # 邮件发送方地址（通常与username一致）
    from: 13818337845@163.com