version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: smart_parking_backend
    ports:
      - "18080:8080"
    volumes:
      # 用于持久化存储用户上传的文件
      - ./volumes/backend/files:/app/files
      - ./volumes/backend/application.yml:/app/application.yml
    depends_on:
      - mysql
      - redis
    networks:
      - smartparking-net

  # 前端 Nginx 服务
  frontend:
    # 构建镜像时，Docker会去上级目录的 'frontend' 文件夹里寻找 Dockerfile
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: smart_parking_frontend
    ports:
      - "80:80"      # 将容器的80端口映射到你电脑的80端口
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - smartparking-net

  # MySQL 数据库服务
  mysql:
    image: mysql:8.0
    container_name: smart_parking_mysql
    ports:
      - "13306:3306" # 将容器的3306端口映射到你电脑的3306端口
    environment:
      MYSQL_ROOT_PASSWORD: 123456  # 设置root用户密码
      MYSQL_DATABASE: parking      # 启动时自动创建名为'parking'的数据库
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - smartparking-net

  # Redis 服务
  redis:
    image: redis:8-alpine
    container_name: smart_parking_redis
    ports:
      - "16379:6379" # 将容器的6379端口映射到主机的6379端口
    networks:
      - smartparking-net
# 定义自定义网络，让所有容器可以通过服务名互相访问
networks:
  smartparking-net:
    driver: bridge